services:
  private-nginx-test:
    image: nginx:alpine
    container_name: private-nginx-test
    networks:
      - internal-proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ROUTER_NAME}.entrypoints=http
      - traefik.http.routers.${ROUTER_NAME}.rule=${ROUTER_RULE}
      - traefik.http.middlewares.${ROUTER_NAME}-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${ROUTER_NAME}.middlewares=${ROUTER_NAME}-https-redirect
      - traefik.http.routers.${ROUTER_NAME}-secure.entrypoints=https
      - traefik.http.routers.${ROUTER_NAME}-secure.rule=${ROUTER_RULE}
      - traefik.http.routers.${ROUTER_NAME}-secure.tls=true
      - traefik.http.routers.${ROUTER_NAME}-secure.service=${ROUTER_NAME}
      - traefik.http.services.${ROUTER_NAME}.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  internal-proxy:
    external: true
