services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${DOMAIN}  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - ./vw-data:/data # the path before the : can be changed
    networks:
      - internal-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ROUTER_NAME}.entrypoints=http
      - traefik.http.routers.${ROUTER_NAME}.rule=${ROUTER_RULE}
      - traefik.http.middlewares.${ROUTER_NAME}-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${ROUTER_NAME}.middlewares=${ROUTER_NAME}-https-redirect
      - traefik.http.routers.${ROUTER_NAME}-secure.entrypoints=https
      - traefik.http.routers.${ROUTER_NAME}-secure.rule=${ROUTER_RULE}
      - traefik.http.routers.${ROUTER_NAME}-secure.tls=true
      - traefik.http.routers.${ROUTER_NAME}-secure.service=${ROUTER_NAME}
      - traefik.http.services.${ROUTER_NAME}.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  internal-proxy:
    external: true
